// <auto-generated />
using System;
using CongresoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CongresoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260926024945_AgregarQrEnviadoAt")]
    partial class AgregarQrEnviadoAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CongresoApi.Models.Asistente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActualizadoEnSistema")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApellidoMaterno")
                        .HasColumnType("text");

                    b.Property<string>("ApellidoPaterno")
                        .HasColumnType("text");

                    b.Property<string>("ClaveExterna")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("CorreoAlterno")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreadoEnSistema")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EntregadoAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntregadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Estacion")
                        .HasColumnType("text");

                    b.Property<string>("EstadoPais")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Matricula")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Origen")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("QrEnviadoAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Seccion")
                        .HasColumnType("text");

                    b.Property<string>("Universidad")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClaveExterna")
                        .IsUnique()
                        .HasFilter("\"ClaveExterna\" IS NOT NULL");

                    b.HasIndex("Correo");

                    b.HasIndex("Matricula")
                        .IsUnique()
                        .HasFilter("\"Matricula\" IS NOT NULL");

                    b.ToTable("Asistentes");
                });

            modelBuilder.Entity("CongresoApi.Models.Escaneo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AsistenteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estacion")
                        .HasColumnType("text");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.Property<string>("RealizadoPor")
                        .HasColumnType("text");

                    b.Property<int>("Resultado")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AsistenteId");

                    b.HasIndex("CreadoEn");

                    b.ToTable("Escaneos");
                });

            modelBuilder.Entity("CongresoApi.Models.Escaneo", b =>
                {
                    b.HasOne("CongresoApi.Models.Asistente", "Asistente")
                        .WithMany()
                        .HasForeignKey("AsistenteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Asistente");
                });
#pragma warning restore 612, 618
        }
    }
}
